# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  ipaddresshandlerexample:
    image: ipaddresshandlerexample
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 88
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:88
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
